cmd/gubernator/config.go
Running gubernator in a kubernetes cluster I've encounted a problem that POD restarts because of some weird issue with logging:
```
time="2019-09-04T07:49:42Z" level=debug msg="Debug enabled"
time="2019-09-04T07:49:42Z" level=debug msg="K8s peer pool config found"
time="2019-09-04T07:49:42Z" level=info msg="Gubernator Listening on 0.0.0.0:81 ..." category=server
(main.ServerConfig) {
GRPCListenAddress: (string) (len=10) "0.0.0.0:81",
EtcdAdvertiseAddress: (string) (len=12) "127.0.0.1:81",
HTTPListenAddress: (string) (len=10) "0.0.0.0:80",
EtcdKeyPrefix: (string) (len=17) "/gubernator-peers",
CacheSize: (int) 50000,
EtcdConf: (clientv3.Config) {
Endpoints: ([]string) (len=1 cap=1) {
(string) (len=14) "localhost:2379"
},
AutoSyncInterval: (time.Duration) 0s,
DialTimeout: (time.Duration) 5s, …
```
=> configure k8s.io/klog to print messages to stderr

cluster/cluster.go, cluster/cluster_test.go, go.mod
Method "cluster.Start(numINstance int)" is optimise by removing build in function "append"
and use build in function "make". Also test cases are added.
=> optimise start instance in cluster

algorithms.go, cache/lru.go
REP-937
Previously there was a disparity between uncached and cached limits when
requesting limit L > remaining R.
* When uncached, R would be set to 0 and OverLimit returned
* When cached, R would be remain R and OverLimit returned
Now, in both instances, R remains unmodified and OverLimit is returned
for that requested limit.
=> Requests over remaining shouldn't change remaining

gubernator.go, peers.go, peers_test.go
This fixes #26 through the following changes:
1.  Add a Shutdown method to PeerClient that will close the request queue, and drain in-flight requests with a timeout. 
2. Change PeerClient.run to send any enqueued requests when the request queue is closed
3. Change PeerClient.run to call interval.Stop on return
4. Reuse existing PeerClients inside Instance.SetPeers
5. Shutdown any removed PeerClients inside Instance.SetPeers
I've been running it in a test environment with both traffic and a volatile peer set, and can confirm that this fixes leaking goroutines issue we were seeing earlier.
=> Fix goroutine leak in `Instance.SetPeers`

global.go, gubernator.go, peers.go
It is possible that while a request is being fulfilled via a peer the peer is removed from the hash ring and it's connection is closed. During this scenario gubernator should attempt to get a new peer and try again.  Related to #28   @joshbohde
=> PIP-693: GetRateLimits() now handles ErrClosing returned from Peers

gubernator.go, peers.go
This is supposed to fix #34
This is my first ever golang code change so no idea if there is another better way to fix this.
Issue was that the wait statement never completed/returned and as a result new endpoint changes ended up as a pending notification as the current notification never completed: https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L638
So this fix explicitly reduces the waitcount after shutting down the peer.
While testing a scenario with stopping multiple instances (2 out of 3) it was also needed to first set the wait count to 2 before starting the go routines.
=> ensure we continue after peers (1 or more) were closed successfully

kubernetes.go
We need this add-function so we can initally detect endpoints and not only when they update. 
This affects the last sidecar and also k8s-services that just don't change.
=> uncomment add function

Makefile, global.go, interval.go, peers.go
Fixes #52  and #51 
TIL: Calling `WaitGroup.Wait()` in separate go routine from `WaitGroup.Add(1)` could cause a race condition if go routine that calls `WaitGroup.Wait()` is called before or at the same time `WaitGroup.Add(1)` is called.
=> Fixed race conditions in Peer.Shutdown() and globalManager

cmd/gubernator/config.go
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
This PR attempts to fix the panic that has been received when `GUBER_MEMBERLIST_ADVERTISE_PORT` port specified.
`panic: reflect.Set: value of type string is not assignable to type int`
=> Fix GUBER_MEMBERLIST_ADVERTISE_PORT value type

config.go, go.sum, kubernetes.go, kubernetesconfig.go, kubernetesconfig_local.go
at sixt, where we are using gubernator already ( and want to use it even more in the future ), we do not have kubernetes services for each of our services. so i added a mechanism that allows to watch for pods directly instead of endpoints. the default behavior however, will not change. 
also we can build/run gubernator with "-tags local" now which lets us test gubernator locally more easily without having to deploy it to the cluster. 
-can specify whether we watch for pods or endpoints while keeping the default behavior
-can run gubernator with -tags local to make use of local k8s config
-update peer list in add function again to get initial list of peers
=> added extended k8s options:

algorithms.go, functional_test.go
I noticed that the leaky bucket algorithm was returning the limit response with the `remaining` value more than the `limit`, which turns out is because the max is set before adding the `leak` to the `remaining` so I've make a simple change and added a test case for it.
Please let me know if anything should change or if this is not the expected behavior.
=> Fix leaky bucket algorithm returning remaining more than limit

.gitignore, config.go, daemon.go, example.conf, gubernator.go, k8s-deployment.yaml
Hello Guys, this PR add support to configure max conn age in grpc server.
It's very important to do a loadbalancing in kubernetes, once the server will renew the connections and force to redirect to others pods.
Regards.
=> add max conn age support

examples/aws-ecs-service-discovery-deployment/README.md, examples/aws-ecs-service-discovery-deployment/cloudwatch_logs.tf, examples/aws-ecs-service-discovery-deployment/ecs.tf, examples/aws-ecs-service-discovery-deployment/ecs_gubernator.tf, examples/aws-ecs-service-discovery-deployment/ecs_iam.tf, examples/aws-ecs-service-discovery-deployment/ecs_service_discovery.tf, examples/aws-ecs-service-discovery-deployment/main.tf, examples/aws-ecs-service-discovery-deployment/sg.tf, examples/aws-ecs-service-discovery-deployment/variables.tf, examples/aws-ecs-service-discovery-deployment/versions.tf, examples/aws-ecs-service-discovery-deployment/vpc.tf
Complement for Pool via dns #99 Pull Request
This is a working example in AWS ECS to start the cluster
Docker image to run can be obtained from `dimaqq/gubernator` with version `latest`
=> Add working example of aws ecs service discovery deployment 

CHANGELOG, benchmark_test.go, gubernator.go
To incorporate the performance improvements recommended in #74 Comments by @valer-cara 
* GetRateLimits() now processes requests synchronously until the key is found to belong to a remote instance. A go-routine is then spawned to handle the remote call. 
While the change did show an improvement, I didn't see the huge improvement I was expecting in `GetRateLimit` tests. The biggest improvement is in the `ThunderingHerd` tests where there is almost a 1x improvement. Users should notice the greatest improvement for rate limits when using `Behavior = GLOBAL` and making many concurrent requests.
```
== Master ==
BenchmarkServer_GetPeerRateLimitNoBatching
BenchmarkServer_GetPeerRateLimitNoBatching/GetPeerRateLimitNoBatching
BenchmarkServer_GetPeerRateLimitNoBatching/GetPeerRateLimitNoBatching-12 …
```
=> Performance improvements in GetRateLimits()

README.md, config.go, daemon.go, dns.go, docker-compose-dns.yml, go.mod, go.sum
This PR brings a new deployment option:
The cloud offers a DNS service with service discovery.
For example in AWS, it's a multi-value DNS entry, where when each new container or instance (from a particular group) is started, an A (and maybe AAAA) record is added to the predefined FQDN. When a container or instance is terminated, it's A (or AAAA) record is automatically removed.
The `gubernator` clients when only need to "talk" to the FQDN to rate limit.
The `gubernator` instances can query this FQDN to discover their neighbours.
Clouds:
* AWS should work (currently testing)
* GCP no idea
* Azure no idea
=> Pool via dns

daemon.go
I tracked down an issue in our system to `BatchTimeout` being left at its default value of 500 ms. I redeployed gubernator with `GUBER_BATCH_TIMEOUT` set to `1s`. Upon startup I see the config in logs which includes the following: `BatchTimeout: (time.Duration) 1s` so I presume I set the envvar properly.
Howver, the test I usually run (which discovered the root cause as `BatchTimeout` being 500 ms) still yielded the same result: some requests would return an error whose cause was content deadline expiration even though the entire request only took ~558 ms for example. I believe the cause is that `Behaviors` is not set in the `Config` passed to `NewV1Instance`. I assume this is unintentional.
Please let me know if I'm wrong here or if I need to change anything else.
=> Fix: Include s.conf.Behaviors in Config for NewV1Instance

algorithms.go, go.sum, mock_store_test.go, store_test.go
Fixed: if a limit duration changes and becomes expired, a stack overflow condition occurs.
Refactor unit tests using stretchr mocking tools.
=> Fix recursion causing stack overflow in `tokenBucket()`.

algorithms.go, functional_test.go
Fixes mailgun/gubernator#118 Basically the fix is to update the cache expiration whenever we calculate a new duration instead of only when request is under the limit. This prevents the cache from expiring more frequently and emptying the leaky bucket.
=> Fix leaky bucket algorithm bucket cache entries expire too frequently

config.go, daemon.go, tls_test.go
Kubernetes does not support readiness and liveliness checks on endpoints that enforce mTLS https://github.com/kubernetes/kubernetes/issues/60952. Before this PR, gubernator running inside a k8s pod would fail to be marked as ready and gubernator logs contained: `http: TLS handshake error from x.x.x.x:x: tls: client didn't provide a certificate`.
This PR adds a new, optional configuration field `HTTPStatusListenAddress` (env var `GUBER_STATUS_HTTP_ADDRESS`). When set, this starts a new http listener at the specified address:port which only serves `/v1/HealthCheck `and has client certificate checking disabled.
=> Enable running gubernator in Kubernetes while enforcing mTLS

Dockerfile, Dockerfile-cli
Today we only build amd64 images for gubernator, and that's silly when go is so good at providing cross-architecture builds.  Lets borrow a page from [the book](https://docs.docker.com/buildx/working-with-buildx/), and use _host-native_ build images (to ignore all of the painful QEMU and golang issues), with a target architecture that can be specified by docker at build time via the `--platform` flag.
This permits us to, for example, simply
```bash
docker buildx build --platform linux/arm64,linux/amd64 -t gubernator:latest .
```
And sing, and dance, and tra la la.  In fact...  check out https://hub.docker.com/repository/docker/jontg/gubernator where I published the results of ☝️
=> Allow multi-arch builds

.github/workflows/on-release.yml
We merged https://github.com/mailgun/gubernator/pull/132 a few months ago, but looks like without augmenting the actual publish step, we don't... actually publish.
=> Publish multi-arch images

deploy/helm/templates/deployment.yaml
Using an internal image hub to fullfil requirement like legal (consisitence build, virus scan, etc.) which is common practice in companies.
The original chart already specified repo and pull policy but missing "pull secret" which required by internal/private repo.
This PR set up the [image pull secret](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) for helm chart, here is an example:
```
image:
repository: example.com/internal/gubernator
pullPolicy: IfNotPresent
pullSecrets:
- name: example-internal-secret
```
=> helm chart add image pull secrets

charts/gubernator/templates/hpa.yaml
Oops, `helm` seem a bit overly eager about making people update the `apiVersion`s. I didn't realize it required 1.23 :)
With this fix, it should work with all the releases supported since July 2019.
=> Add support for pre-1.23 Kubernetes versions

algorithms.go, functional_test.go
This pull request fixes #156.
It's a simple change in both the tokenBucket and leakyBucket algorithms.
Unit tests for both changes were added.
=> fix #156, negative hits when remaining 0

.github/workflows/on-pull-request.yml, .github/workflows/on-release.yml, RELEASE.md, check-version.sh, update-version.sh, version-check.sh
Simplify the version update workflow.
Previously, I have been manually updating the version by:
* Merge PR.
* Commit to `master` with changes to `version`, `CHANGELOG`, and Helm chart versions.
* Create a Github Release with a new version tag in format "v2.0.0-rc.34".
* Expect `on-release` action to launch and pass.
However, there exists conflicting functionality in Github Actions to make automated updates to these files from the version tag.  This means that the workflow is assumed to be instead:
* Merge PR.
* Create Github Release with a new version tag.
* Expect `on-release` action to launch and pass.  This action updates the versions in files.
The apparent outcome is that the files are updated with the appropriate version, however the tag still points to the original commit.  When …
=> Add version consistency check.

config.go, example.conf, tls.go
This will allow folks to block usage of TLS 1.0 and TLS1.1 which have known vulnerabilities.
=> Add environment variable to set minimum TLS version on server tls config

algorithms.go
Token bucket algorithm would reset "remaining" for a request within milliseconds when using behavior DURATION_IS_GREGORIAN.
This is happening because expiry calculation for behavior DURATION_IS_GREGORIAN, was calculated but never updated.
Raising a PR for this issue. #161
=> fix #161 token bucket fix for DURATION_IS_GrEGORIAN

algorithms.go, config.go, gubernator.go, lrucache.go, peer_client.go, workers.go, workers_internal_test.go, workers_test.go
I always found `GubernatorPool` to be confusing, so I renamed it to `WorkerPool` which should make it clearer what the pool is for.
* This PR depends on #180 
* Prefixed all the global Prometheus metrics with `metric` which clearly identifies each as such.
=> Renamed gubernator pool to worker pool

charts/gubernator/templates/hpa.yaml, charts/gubernator/templates/servicemonitor.yaml, charts/gubernator/values.yaml
Hi, I Hope you're doing OK. I've tried to add a `serviceMonitor` template to make metrics scraping easier.
There was also a tiny issue with `hpa` which I've included in this PR. Please let me know if you find any issues with this.
Thank you.
=> Add Service Monitor to helm chart

cmd/gubernator/main.go
```
msg="during tracing.NewResource()" category=gubernator error="error in resource.Merge on resources index 0: cannot merge resource due to conflicting Schema URL"
```
https://github.com/mailgun/gubernator/issues/195
=> Fix startup error due to OTel dependency upgrade.

config.go, global.go
This is a follow-up of https://github.com/mailgun/gubernator/pull/111 which was abandoned.
I don't know if the existing benchmarks would cover this code, but:
With this PR:
```go
[26/10/23 12:27:25] ~/GitHub/gubernator (concurrent-updates) $ go test ./... -bench . -benchtime 5s -timeout 0 -run=XXX -cpu 1 -benchmem
goos: darwin
goarch: amd64
pkg: github.com/mailgun/gubernator/v2
cpu: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
BenchmarkReplicatedConsistantHash/fasthash/fnv1a                100000000               57.23 ns/op            0 B/op          0 allocs/op
BenchmarkReplicatedConsistantHash/fasthash/fnv1                 153649881               41.15 ns/op            0 B/op          0 allocs/op
BenchmarkCache/LRUCache/Sequential_reads                        19600915               424.4 …
```
=> perf: Fanout for async updates in global

.github/workflows/master.yaml, .github/workflows/on-pull-request.yml, Makefile
Close https://github.com/mailgun/gubernator/issues/199
=> ci: run benchmarks on every pr and alert if perf is worse

peer_client_test.go
Fix test failure https://github.com/mailgun/gubernator/actions/runs/7023893758/job/19111445772?pr=204#step:9:319
```
panic: test timed out after 10m0s
running tests:
TestPeerClientShutdown (9m57s)
TestPeerClientShutdown/Batching (9m57s)
goroutine 4053 [running]:
testing.(*M).startAlarm.func1()
/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:2259 +0x1fc
created by time.goFunc
/opt/hostedtoolcache/go/1.21.4/x64/src/time/sleep.go:176 +0x45
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0009d2000, {0x2a05153, 0x16}, 0x2add728)
/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:1649 +0x856
testing.runTests.func1(0x0?)
/opt/hostedtoolcache/go/1.21.4/x64/src/testing/testing.go:2054 +0x85
testing.tRunner(0xc0009d2000, 0xc0008c97c8) …
```
=> test: fix TestPeerClientShutdown

.github/workflows/on-pull-request.yml, Makefile, algorithms.go, cluster/cluster.go, config.go, daemon.go, functional_test.go, global.go, gubernator.go, interval_test.go
To change how `GLOBAL` behavior operates. Previously, the owner of the rate limit would broadcast the computed result of the rate limit to other peers, and the computed result from the owner is returned to clients who submit hits to a peer. However, after some great feed back on #218 and #216 It has become clear that we should instead allow the local peers to compute the result of the request based on the hits broadcast by the owning peer.
In the new behavior a peer will compute the result of the rate limit request and immediately return that computed result. This means that the non owning peer will compute the result with the current `Remaining` value it currently has in it's cache. To put it another way, the peer cache will no longer hold the computed result from the owner. 
In order to …
=> Change global behavior
